# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Firebase CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: git clone
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: npm install and build
      run: |
        npm i
        CI='' npm run build
        
    - name: Archive build
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: git clone
      uses: actions/checkout@v2
    
    - name: Download build
      uses: actions/download-artifact@v2
      with:
        name: build
        path: build
        
    - name: Deploy to Firebase
      uses: w9ids/firebase-action@master
      with:
        args: deploy --only hosting
      env: 
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    
