# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Firebase CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: git clone
      uses: actions/checkout@master
      
    - name: npm install and build
      env: 
        CI: ""
      run: |
        npm install
        npm run build
      
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: lowply/deploy-firebase@v0.0.3
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: flowtok-dev-server
          TARGET_BRANCH: master

    
