# This is a basic workflow to help you get started with Actions

name: Firebase CI/CD v.2

on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install yarn and build
        env:
          CI: ""
        run: |
         npm install yarn
         yarn
         yarn run build
        
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 30d
          projectId: flowtok-dev-server
